name: Lua lint

on: 
  push:
  pull_request:
  workflow_dispatch:

env:
  FILES_TO_CHECK: >-
    .

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1"
        
    - uses: leafo/gh-actions-luarocks@v4.1.0
      with:
        luarocksVersion: "3.7.0"
        
    - name: Install luacheck
      run: luarocks install luacheck

    - name: Luacheck Lint
      id: luacheck
      shell: bash --noprofile --norc {0}
      run: |
        echo "::add-matcher::.github/luacheck-plain.json"
        luacheck ${{ env.FILES_TO_CHECK }} \
          --formatter plain \
          --codes --ranges
        exitcode=${PIPESTATUS[0]}
        echo "::remove-matcher owner=luacheck-plain_error::"
        echo "::remove-matcher owner=luacheck-plain_warning::"
        if [ "$exitcode" -gt 1 ]; then
          exit $exitcode;
        else
          exit 0;
        fi
